---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 12/13/23 10:08 AM
---
local VModelBuilder = eifo.VModelBuilder
local productView = VModelBuilder.new(nil, "Product")
local pcmView = productView:rightJoin("ProductCategoryMember", "productId", "categories")
productView:rightJoin("ProductContent", "productId", "productContents")
local productModel = productView:newVModel()
local conn = eifo.db.conn.redis()
conn:connect()
productModel:loadByKey("p:DEMO_002", conn)
conn:disconnect()
ngx.say(productModel[1].description)
--local vm, paths = productView:lookup(nil, "aaa")
--ngx.log(ngx.DEBUG, table.concat(paths))
