---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 10/31/23 10:19 AM
---

local data = {
    {   eName = "ProductCategory",
        cols = { "productCategoryId", "productCategoryTypeEnumId", "categoryName" },
        vals = {
            {"APP", "PctCatalog", "Apparel"},
            {"NIG", "PctCatalog", "Night Gown"},
            {"SPO", "PctCatalog", "Sport wear"},
            {"UND", "PctCatalog", "Underwear"},
            {"BRA", "PctCatalog", "Bra"},
            {"SHO", "PctCatalog", "Shorts"},
            {"DRE", "PctCatalog", "Dress"},
            {"PAN", "PctCatalog", "Pants"},
            {"AOD", "PctCatalog", "Áo dài"},
            {"PAJ", "PctCatalog", "Pajamas"},
            {"VIT", "PctCatalog", "Vitamins"},
            {"WOM", "PctCatalog", "Women"},
            {"MEN", "PctCatalog", "Men"},
            {"CHI", "PctCatalog", "Children"},
            {"GCMR", "PctCatalog", "Glucosamin and Chondroitin with MSM & Burdock Root"},
            {"GCMT", "PctCatalog", "Glucosamin and Chondroitin with MSM & Turmeric"},
            {"GCMB", "PctCatalog", "Glucosamin and Chondroitin with MSM & Boswellia"}
        }
    },
    {   eName = "ProductCategoryRollup",
        cols = { "productCategoryId", "parentProductCategoryId", "fromDate" },
        vals = {
            {"SPO", "APP", "2023-11-25"},
            {"NIG", "APP", "2023-11-25"},
            {"SPO", "APP", "2023-11-25"},
            {"UND", "APP", "2023-11-25"},
            {"BRA", "APP", "2023-11-25"},
            {"SHO", "APP", "2023-11-25"},
            {"DRE", "APP", "2023-11-25"},
            {"PAN", "APP", "2023-11-25"},
            {"AOD", "APP", "2023-11-25"},
            {"PAJ", "APP", "2023-11-25"},
            {"WOM", "VIT", "2023-11-25"},
            {"MEN", "VIT", "2023-11-25"},
            {"CHI", "VIT", "2023-11-25"},
            {"GCMR", "VIT", "2023-11-25"},
            {"GCMT", "VIT", "2023-11-25"},
            {"GCMB", "VIT", "2023-11-25"},
            {"GCMR", "MEN", "2023-11-25"},
            {"GCMT", "MEN", "2023-11-25"},
            {"GCMB", "MEN", "2023-11-25"},
            {"GCMR", "WOM", "2023-11-25"},
            {"GCMT", "WOM", "2023-11-25"}
        }
    },
    {   eName = "Product",
        cols = { "productId", "productName", "description" },
        vals = {
            { "DEMO_001", "Demo One", "For Demo1"},
            { "DEMO_002", "Demo Two", "For Demo2"},
            { "DEMO_003", "Demo Three", "For Demo3"},
            { "DEMO_004", "Demo Four", "For Demo4"},
            { "DEMO_005", "Demo Five", "For Demo5"},
            { "DEMO_006", "Demo Six", "For Demo6"},
            { "DEMO_007", "Demo Seven", "For Demo7"},
            { "DEMO_008", "Demo Eight", "For Demo8"},
            { "DEMO_009", "Demo Nine", "For Demo9"},
            { "DEMO_010", "Demo Ten", "For Demo10"},
            { "DEMO_011", "Demo Eleven", "For Demo11"},
            { "DEMO_012", "Demo Twelve", "For Demo12"},
            { "DEMO_013", "Demo Thirteen", "For Demo13"},
            { "DEMO_014", "Demo Fourteen", "For Demo14"},
            { "DEMO_015", "Demo Fifteen", "For Demo15"},
            { "DEMO_016", "Demo Sixteen", "For Demo16"},
            { "DEMO_017", "Demo Seventeen", "For Demo17"},
            { "DEMO_018", "Demo Eighteen", "For Demo18"},
            { "DEMO_019", "Demo Nineteen", "For Demo19"},
        }
    },
    {   eName = "ProductContent",
        cols = {"productContentId", "productId", "productContentTypeEnumId", "contentLocation" },
        vals = {
            {"IMG_001", "DEMO_001", "PcntImageUrlSmall", "https://picsum.photos/id/1/300.webp"},
            {"IMG_002", "DEMO_002", "PcntImageUrlSmall", "https://picsum.photos/id/2/300.webp"},
            {"IMG_003", "DEMO_003", "PcntImageUrlSmall", "https://picsum.photos/id/3/300.webp"},
            {"IMG_004", "DEMO_004", "PcntImageUrlSmall", "https://picsum.photos/id/4/300.webp"},
            {"IMG_005", "DEMO_005", "PcntImageUrlSmall", "https://picsum.photos/id/5/300.webp"},
            {"IMG_006", "DEMO_006", "PcntImageUrlSmall", "https://picsum.photos/id/6/300.webp"},
            {"IMG_007", "DEMO_007", "PcntImageUrlSmall", "https://picsum.photos/id/7/300.webp"},
            {"IMG_008", "DEMO_008", "PcntImageUrlSmall", "https://picsum.photos/id/8/300.webp"},
            {"IMG_009", "DEMO_009", "PcntImageUrlSmall", "https://picsum.photos/id/9/300.webp"},
            {"IMG_010", "DEMO_010", "PcntImageUrlSmall", "https://picsum.photos/id/10/300.webp"},
            {"IMG_011", "DEMO_011", "PcntImageUrlSmall", "https://picsum.photos/id/11/300.webp"},
            {"IMG_012", "DEMO_012", "PcntImageUrlSmall", "https://picsum.photos/id/12/300.webp"},
            {"IMG_013", "DEMO_013", "PcntImageUrlSmall", "https://picsum.photos/id/13/300.webp"},
            {"IMG_014", "DEMO_014", "PcntImageUrlSmall", "https://picsum.photos/id/14/300.webp"},
            {"IMG_015", "DEMO_015", "PcntImageUrlSmall", "https://picsum.photos/id/15/300.webp"},
            {"IMG_016", "DEMO_016", "PcntImageUrlSmall", "https://picsum.photos/id/16/300.webp"},
            {"IMG_017", "DEMO_017", "PcntImageUrlSmall", "https://picsum.photos/id/17/300.webp"},
            {"IMG_018", "DEMO_018", "PcntImageUrlSmall", "https://picsum.photos/id/18/300.webp"},
            {"IMG_019", "DEMO_019", "PcntImageUrlSmall", "https://picsum.photos/id/19/300.webp"},
        }
    },
-- {   eName = "ProductStorePromotion",
    --     cols = { "storePromotionId", "productStoreId", "itemDescription", "serviceRegisterId", "sequenceNum", "requireCode", "useLimitPerOrder", "useLimitPerCustomer", "useLimitPerPromotion" },
    --     vals = {
    --         { "PopcBuyGet", "Buy 1 Get 1 Half Off", "BuyGetDiscount", "10", "Y", "2", "4", "10" },
    --         { "PopcNewCustomer", "20 25 Discount for New Customers" }
    --     }
    -- },
    {   eName = "ProductCategoryMember",
        cols = { "productCategoryId", "productId", "fromDate" },
        vals = {
            {"SPO", "DEMO_001", "2023-11-25"},
            {"NIG", "DEMO_002", "2023-11-25"},
            {"SPO", "DEMO_003", "2023-11-25"},
            {"UND", "DEMO_004", "2023-11-25"},
            {"BRA", "DEMO_005", "2023-11-25"},
            {"SHO", "DEMO_006", "2023-11-25"},
            {"DRE", "DEMO_007", "2023-11-25"},
            {"PAN", "DEMO_008", "2023-11-25"},
            {"AOD", "DEMO_009", "2023-11-25"},
            {"PAJ", "DEMO_010", "2023-11-25"},
            {"WOM", "DEMO_009", "2023-11-25"},
            {"MEN", "DEMO_010", "2023-11-25"},
            {"CHI", "DEMO_011", "2023-11-25"},
            {"GCMR", "DEMO_012", "2023-11-25"},
            {"GCMT", "DEMO_013", "2023-11-25"},
            {"GCMB", "DEMO_014", "2023-11-25"},
            {"GCMR", "DEMO_015", "2023-11-25"},
            {"GCMT", "DEMO_016", "2023-11-25"},
            {"GCMB", "DEMO_017", "2023-11-25"},
            {"GCMR", "DEMO_018", "2023-11-25"},
            {"GCMT", "DEMO_019", "2023-11-25"}
        }
    }
}

local submit = ngx.location.capture
local escape = ngx.escape_uri
--local readBody = ngx.req.read_body
--readBody
for k = 1, #data do
    local eName = data[k].eName
    local eCols = data[k].cols
    local eValArray = data[k].vals
    ngx.say("<h3>"..eName.."</h3><ul>")
    for i = 1, #eValArray do
        local urlStr = "/notifyChanges?entityName=".. eName
        local eVals = eValArray[i]
        for j = 1, #eVals do
            urlStr = urlStr.."&".. eCols[j].."="..escape(eVals[j])
        end
        local res = submit(urlStr, { method = ngx.HTTP_GET })
        ngx.say("<li>"..urlStr..": "..res.body) --((res.status == ngx.HTTP_OK and "OK") or res.body).."</li>")
    end
    ngx.say("</ul>")
end
--1. start BO
--2. create a vendor
--3. create a store
--4. start appropriate FO server
--5. create data in BO (all the data will be pushed to FO)