---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 10/11/23 7:55 AM
---
local utils = eifo.utils
ngx.log(ngx.INFO, "URI: ____"..ngx.var.request_uri.."_____")
local route, context = eifo.route:getRoute(ngx.var.request_uri)
local content, err, status
local view = route.view
if not view then
    content, err = route:loadFromFile(context)
    status = content and ngx.HTTP_OK or ngx.HTTP_NOT_FOUND
else
    content, status = view:render(context)
end
if not content then
    utils.responseError(status, "Error") --> TODO: localize messages
    return
end

ngx.header.content_type = route:getContentType()
ngx.status = status
ngx.send_headers()
ngx.print(content)
ngx.eof()
route:saveToFile(content, context)