---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 12/8/23 12:06 AM
---
local store = eifo.store
local token = store:getSessionToken()
ngx.say("const sessionToken = '"..token.."';")
ngx.say("const storeId = '"..store.storeId.."';")
ngx.say("alert(sessionToken);")