---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 9/2/23 12:06 PM
---
local ngx = ngx
local utils = eifo.utils

local cjson = require "cjson"
local function response(resData, httpStatus)
    ngx.header["Content-Type"] = "application/json"
    ngx.status = ngx.HTTP_OK
    ngx.say(cjson.encode(resData))    
    ngx.eof()
end

local tables = {};
local function updateRecord(reqData, conn)
    local entityName = utils.popKey(reqData, "entityName")
    if not entityName then
        return {status="failed", message="Entity Name (key 'entityName') is missing"}
    end
    local action = utils.popKey(reqData, "action")

    local tbl = tables[entityName]
    if not tbl then
        tbl = eifo.db.table[entityName]
        if not tbl then
            return {status="failed", message="Entity '" .. entityName .."' has no definition"}
        end
        tbl = tbl:new({conn = conn})
        tables[entityName] = tbl
    end
    local record, err = tbl:newRecord(reqData)
    if not record then
        return {status="failed", message="Cannot initiate entity value: "..(err or "")}
    end
    ngx.log(ngx.DEBUG, "Table: "..tbl._name..", entityName: "..entityName..", record key: "..record.key..", record: "..(record and utils.toJson(record) or "NIL"))

    local existingRecord = tbl:load({key = record.key}, conn)
    if action == "update" then
        if not existingRecord then
            return {status="failed", message="Record not found", action=action, entityName=entityName, key=record.key}
        end
    end
    local oldVals, newVals, persistErr = record:persist(conn, action == "delete")
    if persistErr then
        return {status="failed", message=persistErr, action=action, entityName=entityName, key=record.key}
    end
    if entityName == "ProductStore" then
        eifo.store:load(conn) -- reload store information
    end
    if existingRecord then
        existingRecord:_notify(oldVals, newVals)
    else
        record:_notify(oldVals, newVals)
    end
    return {status="success", message="ok", action=action, entityName=entityName, key=record.key}
end

    -- 1. Read Request data:
local readReqData = require "resty.reqargs"
local getData, postData, _ = readReqData()
local reqData = utils.mergeRef(getData, postData)
if not reqData or utils.isTableEmpty(reqData) then
    response( {error = "Request data is missing"}, ngx.HTTP_BAD_REQUEST)
    return
end
-- ngx.log(ngx.DEBUG, utils.toString(reqData, ": ", "\n"))
local entityList = reqData["entities"]
if not entityList then
    response( {error = "Request data is missing"}, ngx.HTTP_BAD_REQUEST)
    return
end
ngx.ctx.lang = reqData["language"] or "en"

local connFactory = eifo.db.conn
local conn, errMsg = connFactory.redis()
if not conn then
    ngx.log(ngx.CRIT, "Failed to get DB connection "..errMsg)
    response( {error = "Internal server error "}, 500)
    return
end
local ok, error = conn:connect()
if not ok then
    ngx.log(ngx.ERR, "Cannot get connection: "..(error or "unknown error"))
    conn:disconnect()
    response( {error = "Internal server error "}, 500)
    return
end

local lockKey = "notifyChanges"
conn:incr(lockKey)
local resData = {}
for i = 1, #entityList, 1 do
    local entityData = entityList[i]
    if type(entityData) == "table" and not utils.isTableEmpty(entityData) then
        local result = updateRecord(entityData, conn)
        table.insert(resData, result)
        ngx.log(ngx.DEBUG, "Update result: "..utils.toJson(result))
    else
        table.insert(resData, {status="failed", message="Entity data is missing or invalid"})
        ngx.log(ngx.DEBUG, "Entity data is missing or invalid")
    end
end
ngx.log(ngx.INFO, "Finished updating "..#entityList.." items")

local num = conn:decr(lockKey)
conn:disconnect()
response( {results = resData}, ngx.HTTP_OK)


local ipStr = ngx.shared.cluster:get("IPs")
if ipStr and type(ipStr) == 'string' then
    local ips = utils.splitStr(ipStr, ",")
    local keys = ngx.shared.lock:get_keys()
    for i = 1, #keys, 1 do
        local timePos = string.find(keys[i], "@") or 0
        keys[i] = string.sub(keys[i], 1, timePos - 1)
        for j = 1, #ips, 1 do
            ngx.location.capture("http://"..ips[j].."/del/"..keys[i])
        end
    end
end
ngx.shared.lock:flush_all()


