---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 9/22/23 9:55 AM
---
local utils = eifo.utils
local RequestContext = require("eifo.RequestContext")
local viewClass = require("eifo.view")
local lock = require "eifo.lock"
local ngx = ngx
local Route = {}

function Route:new(routeInfo)
    routeInfo = routeInfo or {}
    routeInfo.pos = routeInfo.pos or 0
    routeInfo.path = routeInfo.path or "/" --> must start and end with "/"
    --ngx.log(ngx.DEBUG, "Route path init: "..routeInfo.path)
    if string.len(routeInfo.path) > 1 then
        if string.sub(routeInfo.path, 1, 1) ~= "/" then
            routeInfo.path = "/"..routeInfo.path
        end
        if string.sub(routeInfo.path, -1, -1) ~= "/" then
            routeInfo.path = routeInfo.path.."/"
        end
    end
    return setmetatable(routeInfo, {__index = self})
end

function Route:getClass()
    local metatbl = getmetatable(self)
    return metatbl and metatbl.__index or nil
end

function Route:getRoute(uriStr, context)
    context = context or RequestContext:new({uri = uriStr})

    local startPos, _ , fileExt = string.find(uriStr, "%.(%a+)$")
    if startPos then
        uriStr = string.sub(uriStr, 1, startPos - 1)
    end
    local pathParams = eifo.utils.getPathParam(uriStr)
    if pathParams[1] == "api" then
        table.remove(pathParams, 1)
    end
    -- if pathParams[#pathParams] == "_EN_"  then
    --     ngx.ctx.lang = "en"
    --     pathParams[#pathParams] = nil
    -- elseif pathParams[#pathParams] == "_VI_" then
    --     ngx.ctx.lang = "vi"
    --     pathParams[#pathParams] = nil
    -- elseif pathParams[#pathParams] == "_CN_" then
    --     ngx.ctx.lang = "cn"
    --     pathParams[#pathParams] = nil
    -- else
    --     ngx.ctx.lang = ngx.ctx.lang or "en" --> default language
    -- end
    local pathPrefix = fileExt and eifo.pathPrefixes[fileExt]
    if pathPrefix and pathParams[1] ~= pathPrefix  then
        table.insert(pathParams, 1, pathPrefix)
    end

    local node = self
    local pos, pathSize = node.pos + 1, #pathParams
    while pos <= pathSize do
        local dirName = pathParams[pos]
        if not node[dirName] then
            if dirName == "no_layout" then  -- path param "no_layout" must be right after the sub route
                context.noLayout = "no_layout"
                pos = pos + 1 -- skip this param
            end
            break
        end
        node = node[dirName]
        pos = pos + 1
    end
    if not node.view and node["index"] then
        node = node["index"]
    end

    local params = {table.unpack(pathParams, pos)}
    if #params > 0 then
        context.params = params
        local view = node.view
        if view then
            context.key = view:getKey(context)
        end
    end

    return node, context
end

function Route:addView(paths, view)
    local fileExt = view.fileExt
    local pathPrefix = fileExt and eifo.pathPrefixes[fileExt]
    if pathPrefix and paths[1] ~= pathPrefix then
        table.insert(paths, 1, pathPrefix)
    end
    ngx.log(ngx.DEBUG, utils.toJson(paths), pathPrefix or " no prefix")

    local numDirs = #paths - 1
    local err = nil
    local route = self
    for i = 1, numDirs, 1 do
        route, err = route:addDir(paths[i], view.outputFile)
        if err then
            break
        end
    end
    if err then
        error(err, 2)
    end
    route = route:addRoute(paths[#paths], view)
    if fileExt then
        route.fileExt = fileExt
    end
end

function Route:addDir(subName, makeDir)
    local subPath = self.name and self.path..self.name.."/" or self.path

    if makeDir then
        local dir = subPath..subName
        local ok, err = utils.mkdir(self.basePath..dir)
        if not ok then
            err = "Cannot create directory for route: "..dir..", error: "..err
            --ngx.log(ngx.ERR, err)
            return self, err
        end
    end

    local routeKey = subName
    local route = self[routeKey]
    if not route then
        route = Route:new({name = subName, path = subPath, pos = self.pos + 1, basePath = self.basePath})
        self[routeKey] = route
    end

    return route
end

function Route:addRoute(subName, subView)
    subView = subView or {}
    local subPath = self.name and self.path..self.name.."/" or self.path

    local routeKey = subName
    if subView.outputFile and subView.requireKey then
        local dir = subPath..subName
        local ok, err = utils.mkdir(self.basePath..dir)
        if ok then
            ok, err = utils.mkdir(self.basePath..dir.."/no_layout")
        end
        if not ok then
            err = "Cannot create directory for route: "..dir..", error: "..err
            ngx.log(ngx.ERR, err)
            return self, err
        end
        subPath = dir.."/"
        subName = nil
    end
    local route = self[routeKey]
    if route then
        assert(route.view == nil or route.view == subView, "There is another view routed to this path: "..(route.view and route.view.name or "nil"))
        route.path = subPath
        route.name = subName
    else
        route = Route:new({name = subName, path = subPath, pos = self.pos + 1, basePath = self.basePath})
        self[routeKey] = route
    end
    if subView then
        if subView.name then --> real view, not emptyView
            route.view = subView
            if subView.table and subView.outputFile then 
                route._observerId = subView.name
                subView.table:_attach(route)
            end
        elseif subView.filePath then
            route.filePath = subView.filePath
        end
    end
    return route
end
function Route:getFileExt()
    if not self.fileExt then
        if self.view and not self.view.templatePath then
            self.fileExt = "json"
        else --> if not self.view then self.filePath must exists:
            local filePath = self.filePath or (self.view and self.view.templatePath)
            local _, _ , fileExt = filePath and string.find(filePath, "%.view%.(%a+)$") or nil, nil, "html"
            self.fileExt = fileExt
        end
    end
    return self.fileExt
end
function Route:getContentType()
    if not self.contentType then
        self.contentType = eifo.contentTypes[self:getFileExt()]
    end
    return self.contentType
end
function Route:getFilePath(context)
    if self.filePath then
        return self.filePath
    end

    context = context or {}
    local params
    local view = self.view
    if view then
        if not view.outputFile then
            return nil
        end
        if view.requireKey then
            local key = view:getKey(context)
            if not key then
                return nil, "Not enough params to generate key for view '"..view.name.."', params: "..utils.toJson(params)
            end
            params = {key}
            context.key = key
        else
            params = {}
        end
    else
        params = context.params or {}
    end
    if self.name then
        table.insert(params, 1, self.name)
    end
    local num = #params
    if num == 0 then
        return nil
    end
    if context.noLayout == "no_layout" then
        params[num + 1] = params[num]
        params[num] = "no_layout"
    end
    context.fileExt = self:getFileExt()
    context.fileName = params[#params]
    params[#params] = nil
    local relPath = #params > 0 and (table.concat(params, "/").."/") or ""
    local filePath = (self.basePath or "")..self.path..relPath
    context.filePath = filePath
    return filePath..context.fileName.."_"..ngx.var.lang.."."..self:getFileExt()
end
function Route:loadFromFile(context)
    local filePath = context.filePath
    local retry
    if not filePath then
        local err
        filePath, err = self:getFilePath(context)
        if not filePath then
            return nil, err
        end
        retry = context.filePath and true or false
    else
        filePath  = filePath..context.fileName
        if context.lang then
            filePath = filePath.."_"..context.lang
        end
        filePath = filePath.."."..self:getFileExt()
        retry = false
    end
    local content, fileErr = utils.read_file(filePath)
    ngx.log(ngx.DEBUG, "Load File "..filePath..": "..(content and "success" or fileErr or " not found"))
    if not content and retry then
        ngx.log(ngx.DEBUG, "Retry load file without lang")
        context.lang = nil
        return self:loadFromFile(context) --> try again without lang
    end
    return content
end
function Route:saveToFile(renderedText, context)
    if not self.view or not self.view.outputFile then
        return
    end
    local outPathFile = self:getFilePath(context)
    assert(outPathFile, self.view.name..": Cannot get output file. context = "..utils.toJson(context))
    local fLock = lock(outPathFile)
    if fLock then -- write renderedText to a static file 
        local f = assert(io.open(outPathFile, "w"))
        f:write(renderedText)
        f:close()
        fLock:unlock()
    end
end
function Route:_update(records, oldVals, newVals)
    local record = records[1]
    self:removeOutFile({key = record.key})
    self:removeOutFile({key = record.key, noLayout = "no_layout"})
end
function Route:removeOutFile(context)
    local outFile = self:getFilePath(context)
    if not outFile then
        return
    end
    local fLock = lock(outFile)
    if fLock then
        os.remove(outFile) --> the updater should remove this lock
        fLock:unlock()
    end
end

return Route