---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 9/22/23 9:55 AM
---

local utils = eifo.utils
local lock = require "eifo.lock"
local template = require("resty.template")
template.load = function (view, plain)
    if plain == true then return view end
    local route, params, noLayout = eifo.route:getRoute(view)
    local content, filePath = route:loadFromFile(params, noLayout)
    if not content then
        local status
        content, status = route:render(params, noLayout)
        if not content or status < 200 or status >= 400 then
            ngx.log(ngx.ERR, "Cannot render layout "..view)
            return view
        end
        route:saveToFile(content, params, noLayout, filePath)
    end
    return content
end
local ngx = ngx

local _view = setmetatable({}, 
    {
        __index = {
            _update = function ()
                ngx.log(ngx.WARN, "_update() is not implemented")
            end
        },
        __eq = function (v1, v2)
            return v1 and v2 and v1.name == v2.name
        end
    }
)

function _view:new(viewInfo)
    local view = setmetatable(viewInfo or {}, self)
    self.__index = self

    local tableDef = viewInfo.tableDef 
                    or assert(viewInfo.tableName and eifo.db.table[viewInfo.tableName])
    ngx.log(ngx.DEBUG, "ViewInfo: "..utils.toJson(viewInfo))
    view.table = tableDef:new({
        toJsonColumns = viewInfo.toJsonColumns,
    })
    local layoutType = type(view.layout)
    if layoutType == "string" then
        view.layoutUri = view.layout
        view.layout = nil
    end
    return view
end
_view.loadView = function(self, fullName, templatePath)
    local viewInfo = require(fullName)
    if not viewInfo or type(viewInfo) ~= "table" then
        return nil
    end

    local view = self:new(viewInfo)
    view.name = fullName
    view.contentType = "application/json; charset=utf-8"
    if not templatePath then
        return view
    end
    
    ngx.log(ngx.INFO, "Initializing template file "..templatePath)
    local content, err = utils.read_file(templatePath)
    if not content then
        ngx.log(ngx.ERR, "Failed to  Initialized template "..templatePath..": "..err)
        return view
    end
    view.template = template.compile(content, "no-cache", true)
    view.contentType = "text/html; charset=utf-8"
    return view
end

_view.getConn = function (...)
    local conn, err = eifo.db.conn.redis()
    if not conn then
        return nil, err
    end
    conn:connect()
    return conn
end
_view.getKey = function (self, params)
    if self.key then
        return self.key
    end
    if not params or not next(params) then
        return nil
    end
    return params.key or (#params == 1 and params[1]) or self.table:generateKey(params)
end
_view.render = function(self, params, noLayout)
    local key = self:getKey(params)
    if not key then
        ngx.log(ngx.INFO, (self.name or "root")..": No search params")
        return nil, ngx.HTTP_BAD_REQUEST
    end

    local conn = self:getConn()
    if not conn then
        ngx.log(ngx.ERR, (self.name or "root")..": Cannot get connection")
        return nil, ngx.HTTP_INTERNAL_SERVER_ERROR
    end
    conn:connect()
    local model = self.table:new({conn = conn})
    ngx.log(ngx.DEBUG, (self.name or "root")..": Loading key "..key)
    local record, err = model:loadByKey(key)
    if not record then
        ngx.log(ngx.INFO, err)
        conn:disconnect()
        return nil, ngx.HTTP_NOT_FOUND
    end

    if not self.template then
        return self.toJson and self:toJson(record) or record:toJson(), ngx.HTTP_OK, "application/json"
    end
    local sHtml = self.template({record = record, main = "{* main *}"}) --> main for layout pre-compile
    if noLayout or not (self.layoutUri or self.layout) then
        return sHtml, ngx.HTTP_OK, "text/html"
    end
    self.layout = self.layout or (self.layoutUri and template.compile(self.layoutUri))
    if self.layout then
        sHtml = self.layout({main = sHtml, record = record})
    end

    conn:disconnect()
    return sHtml, ngx.HTTP_OK
end

return _view