---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 10/10/23 9:30 AM
---
-- TODO: store workPermit in Shared Dict instead of Redis
local utils = eifo.utils
local workPermit = {}
workPermit.seperator = ","
workPermit.create = function(key, evKey, conn)
    key = "wp:"..key
    evKey = workPermit.seperator..evKey
    return conn:append(key, evKey)
end
workPermit.get = function(key, conn)
    local evKeyStr = conn:getdel(key)
    if evKeyStr ~= nil and type(evKeyStr) == "string" then
        return utils.splitStr(evKeyStr, workPermit.seperator)
    end
    return nil, "Work Permit not exist"
end
return workPermit
