---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tnguyen.
--- DateTime: 10/10/23 9:30 AM
---
if not gleecy then
    gleecy = {}
end
if gleecy.workPermit then
    return gleecy.workPermit
end
gleecy.workPermit = {}
local utils = require("gleecy.utils")
gleecy.workPermit.seperator = ","
gleecy.workPermit.create = function(key, evKey, conn)
    key = "wp:"..key
    evKey = gleecy.workPermit.seperator..evKey
    return conn:append(key, evKey)
end
gleecy.workPermit.get = function(key, conn)
    local evKeyStr = conn:getdel(key)
    if evKeyStr ~= nil and type(evKeyStr) == "string" then
        return utils.splitStr(evKeyStr, gleecy.workPermit.seperator)
    end
    return nil, "Work Permit not exist"
end
return gleecy.workPermit
